<a href="https://colab.research.google.com/github/jjhsnail0822/deep-learning-from-scratch-2/blob/master/ch01/1-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 1.1.1 벡터와 행렬

import numpy as np

x=np.array([1,2,3])
x.__class__

numpy.ndarray

In [ ]:
x.shape

(3,)

In [ ]:
x.ndim

1

In [ ]:
W=np.array([[1,2,3],[4,5,6]])
W.shape

(2, 3)

In [ ]:
W.ndim

2

In [ ]:
# 1.1.2 행렬의 원소별 연산

W=np.array([[1,2,3],[4,5,6]])
X=np.array([[0,1,2],[3,4,5]])
W+X

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [ ]:
W*X

array([[ 0,  2,  6],
       [12, 20, 30]])

In [ ]:
# 1.1.3 브로드캐스트

A = np.array([[1,2],[3,4]])
A*10

array([[10, 20],
       [30, 40]])

In [ ]:
A=np.array([[1,2],[3,4]])
b=np.array([10,20])
A*b

array([[10, 40],
       [30, 80]])

In [ ]:
# 1.1.4 벡터의 내적과 행렬의 곱

a=np.array([1,2,3])
b=np.array([4,5,6])
np.dot(a,b)

32

In [ ]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
np.matmul(A,B)

array([[19, 22],
       [43, 50]])